version: "3.6"

services:
        app1:
                image: app1
                container_name: app1
                restart: always
                ports:
                        - 1111:1111

        app2:
                image: app2
                container_name: app2
                restart: always
                ports:
                        - 2222:2222

        app_gw:
                image: app_gw
                container_name: app_gw
                restart: always
                ports:
                        - 80:80
